services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./Server
    container_name: server_container
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /Server/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/taskDB

  client:
    build: ./todolist
    container_name: client_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./todolist:/app
      - /todolist/node_modules

volumes:
  mongo_data:
